// <auto-generated />
using System;
using GameLibrary.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameLibrary.Api.Migrations
{
    [DbContext(typeof(GameLibraryDbContext))]
    partial class GameLibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameLibrary.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An epic adventure in the kingdom of Hyrule",
                            Price = 69.99m,
                            Title = "The Legend of Zelda: Tears of the Kingdom",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A challenging action role-playing game",
                            Price = 59.99m,
                            Title = "Elden Ring",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A mind-flaying adventure of epic proportions",
                            Price = 59.99m,
                            Title = "Baldur's Gate 3",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An open-world action role-playing game set in the future",
                            Price = 49.99m,
                            Title = "Cyberpunk 2077",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bethesda's ambitious space exploration RPG",
                            Price = 69.99m,
                            Title = "Starfield",
                            UpdatedAt = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
